### ISSUE TITLE
fix typo in Graphics driver installation Wiki

### ISSUE THREAD

**Issue by nielsenjared** [NoXPhasma/protondb_faq#17]
The [Ubuntu 18.04 / 18.10 / 19.04 / Linux Mint 19.x:](https://github.com/NoXPhasma/protondb_faq/wiki/Graphics-driver-installation#ubuntu-1804--1810--1904--linux-mint-19x) installation instructions read as follows: 

**Nvidia 440**
```
sudo add-apt-repository ppa:graphics-drivers/ppa
sudo apt update
sudo apt install nvidia-drivers-440
```
**Nvidia 450**
```
sudo add-apt-repository ppa:graphics-drivers/ppa
sudo apt update
sudo apt install nvidia-drivers-450
```
The correct commands are: 
```
sudo apt install nvidia-driver-440
```
and
```
sudo apt install nvidia-driver-450
```

**Comment by NoXPhasma** [comment]
Fixed, thank you!
